services:

  envoy:
    build:
      context: ./envoy
      dockerfile: Dockerfile
    ports:
    - 8001:8001
    - 8080:8080
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml


  envoy-service-a:
    build:
      context: ./envoy-service-a
      dockerfile: Dockerfile
    depends_on:
      service-a:
        condition: service_started
    ports:
    - 3001:3001
    volumes:
      - ./envoy-service-a/envoy.yaml:/etc/envoy/envoy.yaml

  service-a:
    build:
      context: ./service-a
      dockerfile: Dockerfile
    ports:
    - 3000:3000
    volumes:
      - ./service-a/server.js:/app/server.js
    # depends_on:
    #   service-envoy-1:
    #     condition: service_healthy
    #   service-envoy-2:
    #     condition: service_healthy
    # ports:
    # - "${PORT_PROXY:-8080}:8080"
    # - "${PORT_HTTPS:-8443}:8443"
    # - "${PORT_STATS:-8001}:8001"